### PR TITLE
Add GIFI empty description test

### PR DESCRIPTION
**Pull request by ylavoie**
Add test to deal with empty SQL-Ledger GIFI descriptions

### CODE REVIEW

**Comment by ehuelsmann** [comment]
Hmm. I'm not sure I like this test: It's your opinion they should have a description, but there's nothing in the migration that depends on the descriptions being available. In other words: when they're empty, nothing fails to migrate.

**Comment by sbts** [comment]
I agree that GIFI should have descriptions, however, I agree with @ehuelsmann that it's not really a pre-migration test.
Rather it's a Data Validation test that is probably best run on All Databases during a normal upgrade, and after a migration from an external source

**Comment by ylavoie** [comment]
Migration will fail if there is a missing use gifi and another with a missing description

**Comment by ehuelsmann** [comment]
Right. But the failure is due to missing code, not due to missing description.

**Pull request closed without merging**
