### PR TITLE
Ensure the order parameters end up in the URL's query string

### LINKED ISSUE #6151: Cannot sort asset class list table
Fixed Assets > Asset Classes > List Classes > Search(without filtering). Click column header to sort. 

Screen Shot 2021-10-22 at 9 28 25 AM

Screen Shot 2021-10-22 at 9 32 15 AM

### PR DESCRIPTION
**Pull request by ehuelsmann**
When the URL doesn't have a query string already, add and empty one
at the end.

Fixes #6151

### CODE REVIEW

**Comment by aungzwin10** [comment]
@ehuelsmann Any update regarding this? Please feel free to ask if you need more information.

**Comment by ehuelsmann** [comment]
@aungzwin10 I'm not sure I can fix this problem in the current code base: it seems that the query string is missing in the original request, which makes the code fail to return the script plus the query string; this would normally be caused by the fact that the request is a POST request -- i.e. a request without a query string.

**Comment by aungzwin10** [comment]
@ehuelsmann Thanks for explaining details, I think the request should be changed to GET since we fetch data.

**Comment by ehuelsmann** [comment]
> @ehuelsmann Thanks for explaining details, I think the request should be changed to GET since we fetch data.

Agreed. Do you have a point where you think this needs to be changed?

**Comment by aungzwin10** [comment]
@ehuelsmann 
Yes. If it is because of POST method, we can change the form method to GET in this line.
https://github.com/ledgersmb/LedgerSMB/blob/e6bec51b6d854af7c25ec843b910a5b1344015c0/UI/asset/search_class.html#L5

I tested without current PR changes, it works well.

**Comment by ehuelsmann** [comment]
@aungzwin10 this new PR should fix the sorting/ordering problems you've reported.

**Comment by aungzwin10** [comment]
Yes, it fix ordering issue. Thank you

**Comment by ehuelsmann** [comment]
Thanks for confirming!

**Pull request merged**
