### PR TITLE
no critic ProhibitExplicitReturnUndef

### PR DESCRIPTION
**Pull request by ziuq**
to allow enforcement.

### CODE REVIEW

**Comment by ehuelsmann** [comment]
I really doubt we want to enforce "ProhibitExplicitReturnUndef", because `return undef;` and `return;` are semantically different. I know we have discussed this before and that we don't have the same view on returning undef from a function due to the fact that it may be used in array context.

However, advice from outside our community was to explicitly return undef everywhere where we currently `return;`. Adding @einhverfr and @sbts for more review and discussion here.

**Comment by ziuq** [comment]
Fixing "bad" code is not what perlcritic is about.  It seems that way when we critique and fix all the trivial errors.  Generating "good" new code is the purpose and that only starts when policies are in place.

Yes, I do not think a _RequireExplicitReturnUndef_ policy is good.  Looking at CPAN and tallying violations and no-critics on all the not-my Perl code installed on my personal machine, I find I am with the majority opinion.   The main argument given for _RequireExplicitReturnUndef_ is a version of "if you are incapable of understanding context you can do this".   I do not believe this group has that incapacity.

I do understand the devilish appeal of saving time by fewer keystrokes and by learning the least necessary to handle a task.   Sometimes those even work.

cloc on system Perl dirs:
Language                             files          blank        comment           code
Perl                                  4251         278864         543658        1170138

Violations:
perlcritic -s with   ProhibitExplicitReturnUndef EmptyReturn
/usr/*                                     2107               2673
lsmb-master/old                         5                     7
lsmb-master/lib                        37                   16

No-Critics in place:

Total                                       613
With a name                          467
"*Return*"                                19
"*EmptyReturn*"                       0
"*ProhibitExplicitReturnUndef*" 7

**Comment by ehuelsmann** [comment]
> The main argument given for RequireExplicitReturnUndef is a version of "if you are incapable of understanding context you can do this". I do not believe this group has that incapacity.

Right. I think that's correct. However, we want to leave the project in a state which makes it easy to contribute for others as well (not limited to those who are already way into Perl).

**Comment by ehuelsmann** [comment]
The above comment meaning: I'm still very much in doubt which way to go. (Either way, I think we should introduce a critic to enforce it that way, because otherwise we'll end up with a mixed style code base...)

**Pull request closed without merging**
