### PR TITLE
Add '--prepare-only' option to 'create' command to prepare existing databases

### PR DESCRIPTION
**Pull request by walidmujahid**
Previously added a new command, now this this pull request is refactor to add a --prepare-only option to the ledgersmb-admin create command, enabling users to prepare an existing database for use with LedgerSMB without needing to recreate it. This integration keeps the command set concise and aligns with existing workflows.

### Rationale

In some environments, especially when using managed database services, the database is created via the service provider's dashboard or API, and users may not have the ability or desire to recreate it using the `ledgersmb-admin create` command. The existing `create` command calls `$self->create` in the `create_and_load` sub in `LedgerSMB::Database`, which attempts to create the database, making it unsuitable in these cases.

By adding the --prepare-only option, we allow the create command to:

- Skip the database creation step when the database already exists.
- Perform the necessary preparation steps to make the database ready for use with LedgerSMB.
- Provide a single command that can handle both creation and preparation, simplifying usage.
- 
#### Use Case:

When deploying LedgerSMB on platforms like DigitalOcean App Platform, users may:

- Create a managed PostgreSQL database via the provider's dashboard.
- Deploy LedgerSMB as a containerized application connected to this database.
- Need to prepare the existing database for use with LedgerSMB without recreating it.

The --prepare-only option facilitates this deployment workflow by preparing the database accordingly.

#### Reference:

This addition is connected to the issue discussed in [Issue #8411](https://github.com/ledgersmb/LedgerSMB/issues/8411) and specifically the workaround mentioned in [this comment](https://github.com/ledgersmb/LedgerSMB/issues/8411#issuecomment-2388659236).

#### Notes:

- The help documentation and usage examples have been updated accordingly.

### CODE REVIEW

**Comment by ehuelsmann** [comment]
Hi! Congratulations on your understanding of the code base! You have come all the way to this PR, which is technically completely correct. The fact that the tests fail is a minor technicality you wouldn't have found in the code base anyway. 

I completely understand your use-case and would like to integrate this functionality into the code base. I'm wondering if it wouldn't make more sense to add a flag (`--prepare-only`?) to the `ledgersmb-admin create` command.

**Comment by walidmujahid** [comment]
@ehuelsmann You are are right. It would make sense to make it a flag for the `create` command. I can rework it tonight, God willing.

**Comment by walidmujahid** [comment]
@ehuelsmann I've refactored to add a `--prepare-only` option to the `create` command and I've removed the new command I had previously proposed.

**Comment by ehuelsmann** [comment]
@walidmujahid Thanks! And congrats on this contribution!

I'm wondering about the other PRs, really, because it's project policy *not* to add new features to release branches, unless it's absolutely impossible to move a user forward without releasing a new function. However, I'd argue that the `ledgersmb-admin` tool is sufficiently obscure so that the chance of this PR breaking a workflow that's vital to someone, is highly unlikely. I'll merge the other PRs too.

By the way, please do note that 1.10 will see EOL (end-of-life) on October 8, so features like these are less important on 1.10 (fixes, though, especially if limited in number of lines changed, can go in until October 8).

**Comment by walidmujahid** [comment]
@ehuelsmann Thank you very much for accepting my contribution. Do you have a document outlining your policies for contributors? I may make contributions in the future and would like to keep your system in mind so I am not messing anything up.

**Comment by ehuelsmann** [comment]
Hi,

Yes, we have some policies written up on https://ledgersmb.org/community-guide/community-guide/development ; the bit on the backports is in https://ledgersmb.org/content/releasing -- the release branch policy. I think the use of the community guide on the Drupal site probably is no longer what developers expect. We'll need to discuss how to handle publishing this information in a way that developers will be able to easily find it.

**Comment by walidmujahid** [comment]
@ehuelsmann maybe adding a CONTRIBUTING.md might be helpful? 

I put up the idea here: https://github.com/ledgersmb/LedgerSMB/discussions/8423#discussion-7278247

**Pull request merged**
